# Generated by Django 6.0.4 on 2026-04-20 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_country_name_alter_profile_age_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='country_id',
            field=models.CharField(max_length=2),
        ),
    ]
